version: 2
updates:
  - directory: /
    package-ecosystem: gradle
    schedule:
      interval: weekly
    assignees:
      - rainer-prosi
    groups:
      junit:
        patterns:
          - "junit*"
          - "org.junit*"
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
    assignees:
      - MichelHartmann
      - rainer-prosi